### ISSUE TITLE
calculating Moran's I using xy coordinates with multiple groups

### ISSUE THREAD

**Issue by skim245** [mcooper/moranfast#3]
Dear @mcooper, 

I have a spatial data (x & y cooridnates) from a tissue histology image and 
would like to use moranfast to calculate moran's I. 
are there way to incorporate "grouping" conditions to do this calculation? 

and quick question on 
        moranfast(x, c1, c2, alternative = "two.sided")
what exactly is "x" value in moranfast function? 

Thank you in advance!

**Comment by mcooper** [comment]
I'm not aware of ways to incorporate grouping conditions.

`x` value is the value that you are checking to see if it has spatial autocorrelation.
